export const managementProfiles = {
    "philip-n": {
        name: "Dr. Philip N.",
        role: "Ag Director",
        bio: "Dr. Philip N. is a ................",
        image: "/placeholder.svg?height=400&width=400",
        email: "philip.n@csppp.com",
        linkedin: "https://www.linkedin.com/in/philip-n",
        twitter: "https://twitter.com/philip_n_ceo",
        achievements: [
            "Led CSPPP to achieve a 300% growth in patient outreach over 5 years",
            "Pioneered the implementation of AI-driven diagnostic tools in rural healthcare centers",
            "Recipient of the 'African Healthcare Leader of the Year' award in 2022",
            "Published over 50 papers in leading medical journals on healthcare management in developing countries",
        ],
    },
    "james-erhurh": {
        name: "Dr. James Erhurh",
        role: "Deputy Director",
        bio: "Dr. James Erhurh is a .............",
        image: "/placeholder.svg?height=400&width=400",
        email: "james.erhurh@csppp.com",
        linkedin: "https://www.linkedin.com/in/james-erhurh",
        twitter: "https://twitter.com/dr_james_erhurh",
        achievements: [
            "Developed a groundbreaking treatment protocol for malaria, reducing mortality rates by 40%",
            "Led a team that successfully contained three Ebola outbreaks in West Africa",
            "Awarded the 'Excellence in Medical Research' by the African Medical Association",
            "Holds 3 patents for innovative medical devices designed for use in resource-limited settings",
        ],
    },
    "bashir-gambo": {
        name: "Bashir Gambo",
        role: "Head of Admin",
        bio: "Bashir Gambo is a ................",
        image: "/placeholder.svg?height=400&width=400",
        email: "bashir.gambo@csppp.com",
        linkedin: "https://www.linkedin.com/in/bashir-gambo",
        twitter: "https://twitter.com/bashir_gambo_cfo",
        achievements: [
            "Secured over $100 million in funding and grants for CSPPP's expansion projects",
            "Implemented a cost-saving strategy that reduced operational expenses by 25% without compromising service quality",
            "Developed an innovative micro-insurance model that has provided healthcare coverage to over 1 million low-income individuals",
            "Named 'CFO of the Year' by the African Business Journal in 2023",
        ],
    },
    "ado-sule": {
        name: "Ado Sule",
        role: "Adminstrative officer",
        bio: "Ado Sule is a ................",
        image: "/placeholder.svg?height=400&width=400",
        email: "ado.sule@csppp.com",
        linkedin: "https://www.linkedin.com/in/ado-sule",
        twitter: "https://twitter.com/ado_sule_ops",
        achievements: [
            "Redesigned CSPPP's supply chain, reducing drug stockouts by 80% in rural health centers",
            "Implemented a telemedicine program that now serves over 500,000 patients annually in remote areas",
            "Led the digital transformation of CSPPP's operations, resulting in a 50% increase in operational efficiency",
            "Recognized as one of the 'Top 40 Under 40' leaders in African Healthcare by HealthCare Africa magazine",
        ],
    },
    "nadi-muhd": {
        name: "Nasfisa Muhd",
        role: "Information & Communication Officer",
        bio: "Nasfisa Muhd is a ................",
        image: "/placeholder.svg?height=400&width=400",
        email: "nasfisa.muhd@csppp.com",
        linkedin: "https://www.linkedin.com/in/nasfisa-muhd",
        twitter: "https://twitter.com/nasfisa_muhd_tech",
        achievements: [
            "Developed an AI-powered diagnostic app that has been adopted by over 1,000 healthcare facilities across Africa",
            "Led the creation of a blockchain-based health records system, improving data security and interoperability for millions of patients",
            "Spearheaded the launch of CSPPP's Innovation Lab, which has incubated 20+ health-tech startups",
            "Awarded the 'Women in Tech Leadership' award by the African Technology Foundation in 2023",
        ],
    },
};